### ISSUE TITLE
where to find the ribbon?

### ISSUE THREAD

**Issue by jjgalvez** [tankwyn/WPS-Zotero#1]
I just installed WSP , zotero, and wps-zotero and when I launch wsp I can't seem to find how to insert a zotero citation. Where do I find it or which ribbon is it in? 

Specifically the zotero ribbon does not seem to be loaded

**Comment by tankwyn** [comment]
What version of WPS are you using? Have you tried to uninstall/install the addon? Is there an error or something occurred during the execution of install.sh?

发自我的iPhone

在 2023年9月13日，上午4:27，Jose Galvez ***@***.***> 写道：

﻿

I just installed WSP , zotero, and wps-zotero and when I launch wsp I can't seem to find how to insert a zotero citation. Where do I find it or which ribbon is it in?

Specifically the zotero ribbon does not seem to be loaded

**Comment by jjgalvez** [comment]
I'm using version 11.1.0.11704, I'm not getting any errors that I can see, although admittedly I'm not sure where to see them

**Comment by tankwyn** [comment]
Well, you did executed the install.sh script, do you? There is a directory path string ended by “jsaddon” in it, you can check if there’s a wps-zotero_0.0.2 directory and jsaddons.xml in it. If so, please upload the content of that xml file so we can see why the addon is not registered.

在 2023年9月13日，上午8:16，Jose Galvez ***@***.***> 写道：

﻿

I'm using version 11.1.0.11704, I'm not getting any errors that I can see, although admittedly I'm not sure where to see them

**Comment by jjgalvez** [comment]
<jsplugins>
  <jsplugin name="wps-zotero" type="wps" url="http://127.0.0.1:3889/" version="0.0.2"/>
</jsplugins>

**Comment by tankwyn** [comment]
> ```
> <jsplugins>
>   <jsplugin name="wps-zotero" type="wps" url="http://127.0.0.1:3889/" version="0.0.2"/>
> </jsplugins>
> ```

I seem to know what's going wrong now. You're using the common edition of WPS, I wasn't aware it exists on Linux, try put the attached file (unzip it first) in the jsaddons directory and restart WPS. By the way, the pro edition is recommended for it's free of ads and bullshits. You can download the pro edition from https://linux.wps.cn/ by clicking the big blue button.

[publish.xml.zip](https://github.com/tankwyn/WPS-Zotero/files/12592298/publish.xml.zip)

**Comment by jjgalvez** [comment]
unfortunately that gave me the same results. I am beginning to wonder if it is an issue with Arch, I will try and install it on a different distro in virtualbox

**Comment by tankwyn** [comment]
> unfortunately that gave me the same results. Decided to test whether the issues are related to how this is installed in Arch from the AUR, by installing Suse in virtualbox and installing directly from the website. Bottom line, it works just fine in Suse and not in Arch so I'm sure it's an issue with Arch. I'll keep look into how it's installed and see if I can fix that and then give this another try.

That is wierd. What approach exactly did you take for installing WPS on Arch? For as far as I know, WPS only provides deb and rpm installers.  Hmm, why don't you take a look at ~/.local/share/Kingsoft/, there should be all sorts of things living under it if WPS was installed correctly. Otherwise, it will most probably be a problem between WPS and Arch.

**Comment by jjgalvez** [comment]
I installed it from the AUR (https://aur.archlinux.org/packages?K=wps-office) which uses the deb package as the base. when I run wps yes  the .local/share/Kingsoft folder is created and populated properly, at least comparing it with the SUSE version. I'm posting the same question to the an Arch forum. I'll reply back here for completeness if I get a satisfactory answer.

**Comment by jjgalvez** [comment]
just wanted to follow up that WPS doesn't seem to work well on Arch, however I installed it on tumbleweed via distrobox and it runs as expected as does your plugin.  Thanks you I would consider this issue closed and will close it.
