### ISSUE TITLE
Zotero7提示连接异常Network error

### ISSUE THREAD

**Issue by muxkin** [tankwyn/WPS-Zotero#15]
能安装这个插件，但是在wps中使用的时候提示：
WPS-Zotero: Network error occurred, is Zotero running?
![image](https://github.com/tankwyn/WPS-Zotero/assets/70116348/9b49dbba-fd33-4e12-8adb-56f79444d916)

**Comment by muxkin** [comment]
已解决，是我没有将python设置系统变量的问题

**Comment by 0mi-manchi** [comment]
> 已解决，是我没有将python设置系统变量的问题

请问您是如何解决的啊，怎么设置系统变量呢

**Comment by HuTaoJiaZiAckerman** [comment]
[请参考](https://github.com/tankwyn/WPS-Zotero/issues/16#issuecomment-1875432277)

我是启动了安装目录下的proxy.py，使用`python proxy.py`，就可以正常使用了。
