### ISSUE TITLE
无法在macOS中执行安装命令

### ISSUE THREAD

**Issue by Tinyu-Zhao** [tankwyn/WPS-Zotero#17]
<img width="682" alt="image" src="https://github.com/tankwyn/WPS-Zotero/assets/44396641/706c52ba-6203-4bf5-9511-cb0f5bfc9bc4">

**Comment by tankwyn** [comment]
WPS的JSAPI目前不支持macos，安装脚本没考虑macos

**Comment by Tinyu-Zhao** [comment]
> WPS的JSAPI目前不支持macos，安装脚本没考虑macos

谢谢解答
