### ISSUE TITLE
提前下载好编程喝插件，编程结束后插件无反应

### ISSUE THREAD

**Issue by iamlgdm** [tankwyn/WPS-Zotero#19]
跟着教程操作，编程结束后打开zotero和wps，但是zotero功能点击后无反应是为什么呢？
![image](https://github.com/tankwyn/WPS-Zotero/assets/158118731/fdc9ed10-b98c-4fd1-a722-c7474a6bfea3)

**Comment by iamlgdm** [comment]
而且红框里的还是问号

**Comment by pepper725** [comment]
请问你是怎么解决的
