### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by cslxiao** [tankwyn/WPS-Zotero#21]
Nice job!
I have the following problem:
Ubuntu 20.04.6 LTS
WPS - 正式版
v11.1.0.11698-release
/opt/kingsoft/wps-office/office6
Linux version 5.15.0-94-generic (buildd@lcy02-amd64-118) (gcc (Ubuntu 9.4.0-1ubuntu1~ 20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #104~20.04.1-Ubuntu SMP Tue Jan 16 13:34:09 UTC 2024
Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz
SDRAM:13.2/31.1GB
```
Traceback (most recent call last):
  File "./install.py", line 142, in <module>
    register(XML_PATHS['jsplugins'], 'jsplugins', rec)
  File "./install.py", line 136, in register
    assert(len(pos) > 0)
```
Is it the problem of ```.local/share/Kingsoft/wps/jsaddons/jsplugins.xml```?

**Comment by SwissNL** [comment]
First of all: Thank you for this Plugin.
Finally Zotero in WPS Office. 

Debian "testing" 6.6.15-amd
WPS 11.1.0.11719

I have the plugin installed as root, and there it works. But as user, I don't get it working.
I have the same message as cslxiao with the addition of "AssertationError".

What am I doing wrong? I cannot find any documentation on this problem....

Thanks!!!

**Comment by tankwyn** [comment]
This problem has now been addressed. Please download the latest repo and refresh your installation.

**Comment by cslxiao** [comment]
> This problem has now been addressed. Please download the latest repo and refresh your installation.

seems not. I tried the latest ones but still with the same problem.

**Comment by cslxiao** [comment]
good job!
