### ISSUE TITLE
有一个fuck的文本文件是插件生成的吗

### ISSUE THREAD

**Issue by bigben446** [tankwyn/WPS-Zotero#24]
看着很尴尬，换成zotero-wps也行啊，在哪儿可以改？

**Comment by tankwyn** [comment]
已经删了，更新一下

在 2024年4月8日，上午9:23，bigben446 ***@***.***> 写道：

﻿

看着很尴尬，换成zotero-wps也行啊，在哪儿可以改？

**Comment by bigben446** [comment]
好的，谢谢啦
