### ISSUE TITLE
WPS里面之前的旧版的zotero扩展无法删除

### ISSUE THREAD

**Issue by windbd** [tankwyn/WPS-Zotero#27]
1.参考了
“https://zotero-chinese.com/user-guide/wps-plugin#_3-%E5%A6%82%E4%BD%95%E5%8D%B8%E8%BD%BD-wps-%E5%AE%89%E8%A3%85%E7%9A%84%E6%97%A7%E7%89%88-zotero-%E6%89%A9%E5%B1%95”
中的做法，没有在目录中找到对应的文件
2.现在WPS里面有两个zotero扩展，左边的无法使用
![image](https://github.com/tankwyn/WPS-Zotero/assets/38740381/3544be11-920a-4907-8c9d-26e3ae5fae24)

**Comment by tankwyn** [comment]
你可以在word首选项里的“加载项”选项卡找到Zotero官方插件的位置（若没安装msoffice，在wps也可以通过类似的方式查到）：
![image](https://github.com/tankwyn/WPS-Zotero/assets/14008274/027dcfaf-d36e-4897-afcc-3281904235ef)
可以禁用或直接去删除。

**Comment by windbd** [comment]
tha太感谢了
