### ISSUE TITLE
Is Export button used for converting this document to word?

### ISSUE THREAD

**Issue by l0o0** [tankwyn/WPS-Zotero#3]
I want to know what this Export button does.  

![图片](https://github.com/tankwyn/WPS-Zotero/assets/2743744/fce113fe-a4db-4841-9934-632fad915afe)

When I click this button, this WPS document will be converted to Word, which will be more compatible?

**Comment by tankwyn** [comment]
It does the same as clicking the "switch to a different word processor" button in document preferences window. In our case, the document should already be compatible with MS Word, but the exported document is compatible with all supported word processors beyond WPS and MS Word, for example, Google Docs, LibreOffice.

I made this available in the ribbon to improve functionality discovery.

**Comment by l0o0** [comment]
Thank you for your answer. Your work helps us a lot. I've write a post about your work https://mp.weixin.qq.com/s/37mqQB5rEfsdgqIxw53Z5A

**Comment by tankwyn** [comment]
> Thank you for your answer. Your work helps us a lot. I've wrote a post about your work https://mp.weixin.qq.com/s/37mqQB5rEfsdgqIxw53Z5A

Great! Much appreciated!
