### ISSUE TITLE
Add citation shortcut

### ISSUE THREAD

**Issue by ashfaq92** [tankwyn/WPS-Zotero#4]
Thanks for the great work!
Is there any keyboard shortcut to add zotero citation (i mean, to open add/edit citation dialogue)>

**Comment by tankwyn** [comment]
Unfortunately, that seems not possible from what I know. In WPS or MS Office, one can only bind shortcuts to built-in commands.

**Comment by tankwyn** [comment]
On Windows you can now insert a citation by holding 'Alt' and hit 'C' twice. However this won't work on Linux. The Linux version of WPS doesn't support this feature.

**Comment by venomega** [comment]
in linux, a global hotkey can be added, you can bind a hotkey to a command, if this awesome addon, could act as a client to himself ( something like *python proxy.py citation*) it could be possible support keybinds, and not just for add/edit citations

**Comment by tankwyn** [comment]
> in linux, a global hotkey can be added, you can bind a hotkey to a command, if this awesome addon, could act as a client to itself ( something like _python cli.py citation_) it could be possible to support keybinds, and not just for add/edit citations

The main functionality is implemented in the WPS addon, not a python script, proxy.py is only a simple script adding CORS response for HTTP requests.
