### ISSUE TITLE
Adding to Quick Access Toolbar

### ISSUE THREAD

**Issue by ashfaq92** [tankwyn/WPS-Zotero#5]
Adding the Zotero commands to Quick Access Toolbar not working.

![image](https://github.com/tankwyn/WPS-Zotero/assets/28701122/71dd281a-433b-4381-b750-d65b33bc254e)

**Comment by tankwyn** [comment]
This is mostly likely a problem with WPS. I've tested with another addon using the JS API, still can't add buttons to quick access toolbar. You can send a feedback to WPS to report this problem.
