### ISSUE TITLE
Zotero button not appearing

### ISSUE THREAD

**Issue by wobblyhen920** [tankwyn/WPS-Zotero#7]
First, thank you so much for this addon.

I think it's not working on my box - I can't find any Zotero icon on any ribbon tab, or elsewhere.  But maybe I'm not getting something?

Linux Mint 21.2 with WPS 11.1.0.11698. Zotero is opened. I tried to restart both WPS Writer and Zotero multiple times and to use "python3 proxy.py kill". 

Thank you!

![Screenshot from 2023-10-09 13-31-01](https://github.com/tankwyn/WPS-Zotero/assets/146888933/637b5537-cda9-402f-ae63-f05e4c43064f)

**Comment by tankwyn** [comment]
> First, thank you so much for this addon.
> 
> I think it's not working on my box - I can't find any Zotero icon on any ribbon tab, or elsewhere. But maybe I'm not getting something?
> 
> Linux Mint 21.2 with WPS 11.1.0.11698. Zotero is opened. I tried to restart both WPS Writer and Zotero multiple times and to use "python3 proxy.py kill".
> 
> Thank you!
> 
> ![Screenshot from 2023-10-09 13-31-01](https://user-images.githubusercontent.com/146888933/273572056-637b5537-cda9-402f-ae63-f05e4c43064f.png)

Your WPS version seems a bit outdated, mine is on 11.1.0.11704. How about you try install the latest version of WPS?

**Comment by wobblyhen920** [comment]
I uninstalled the Flatpak version I had and installed the deb package on the WPS website. That did the trick. 
Thanks so much, this works wonderfully.
